init:
	go get ./...
	go get github.com/jteeuwen/go-bindata/...

test:
	go test ./...

build:
	cd templates && go-bindata -pkg templates -ignore=bindata templates
	go build ./...

.PHONY: init, test, build
